package io.github.cdsap.artifacttransform.cli.output

import com.google.gson.Gson
import io.github.cdsap.artifacttransform.cacheEffectivenessByTransformActionType
import io.github.cdsap.artifacttransform.dependencySortedByDuration
import io.github.cdsap.artifacttransform.durationByAttributeTransition
import io.github.cdsap.artifacttransform.durationByAvoidanceOutcome
import io.github.cdsap.artifacttransform.durationByBuildScan
import io.github.cdsap.artifacttransform.durationByTransformActionType
import io.github.cdsap.artifacttransform.extractName
import io.github.cdsap.artifacttransform.overallCacheHitRate
import io.github.cdsap.artifacttransform.sortedByDurationDescending
import io.github.cdsap.artifacttransform.totalAvoidableMissDuration
import io.github.cdsap.artifacttransform.totalByTransformActionType
import io.github.cdsap.geapi.client.model.ArtifactTransform
import java.io.File

/**
 * Writes a self-contained, interactive HTML report. Chart.js is bundled as a resource and inlined,
 * so the report renders offline with no external requests.
 */
class HtmlOutput(
    private val transforms: List<ArtifactTransform>,
    private val single: Boolean
) {
    private data class ChartSpec(
        val id: String,
        val type: String,
        val indexAxis: String,
        val title: String,
        val labels: List<String>,
        val data: List<Long>,
        val valueLabel: String
    )

    fun writeHtml() {
        val prefixFile = if (single) "single-" else ""
        val html = "${prefixFile}artifact-transforms-${System.currentTimeMillis()}.html"
        val startTimestamp = System.currentTimeMillis()
        File(html).writeText(render())
        val endTime = System.currentTimeMillis()
        println("File $html created in ${endTime - startTimestamp} ms")
    }

    private fun render(): String {
        val chartJs = javaClass.getResourceAsStream("/chart.umd.min.js")
            ?.bufferedReader()?.use { it.readText() }
            ?: error("chart.umd.min.js resource not found")

        val charts = buildCharts()
        val chartsJson = Gson().toJson(charts)

        val buildScans = transforms.groupBy { it.buildScanId }.count()
        val hitRate = (transforms.overallCacheHitRate() * 100).roundTo(2)
        val avoidableMs = transforms.totalAvoidableMissDuration().toLong()

        return buildString {
            append(
                """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>Artifact Transform Report</title>
                <style>
                  :root { --bg:#0f1117; --card:#1a1d27; --border:#2a2e3a; --text:#e5e9f0; --muted:#9aa3b2; --accent:#6aa6ff; }
                  * { box-sizing: border-box; }
                  body { margin:0; background:var(--bg); color:var(--text);
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
                  header { padding:24px 32px; border-bottom:1px solid var(--border); }
                  h1 { margin:0; font-size:20px; font-weight:600; }
                  .sub { color:var(--muted); font-size:13px; margin-top:4px; }
                  .stats { display:flex; flex-wrap:wrap; gap:16px; padding:24px 32px; }
                  .stat { background:var(--card); border:1px solid var(--border); border-radius:10px;
                    padding:16px 20px; min-width:160px; }
                  .stat .v { font-size:24px; font-weight:700; }
                  .stat .l { color:var(--muted); font-size:12px; margin-top:4px; text-transform:uppercase; letter-spacing:.04em; }
                  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(420px,1fr)); gap:20px; padding:0 32px 40px; }
                  .card { background:var(--card); border:1px solid var(--border); border-radius:12px; padding:20px; }
                  .card h2 { margin:0 0 14px; font-size:14px; font-weight:600; }
                  .canvas-wrap { position:relative; height:320px; }
                  footer { color:var(--muted); font-size:12px; padding:0 32px 32px; }
                </style>
                <script>$chartJs</script>
                </head>
                <body>
                <header>
                  <h1>Artifact Transform Report</h1>
                  <div class="sub">${if (single) "Single build scan" else "Aggregated builds"} &middot; generated by artifacttransform</div>
                </header>
                <section class="stats">
                  <div class="stat"><div class="v">${transforms.size}</div><div class="l">Total transforms</div></div>
                  <div class="stat"><div class="v">$buildScans</div><div class="l">Build scans</div></div>
                  <div class="stat"><div class="v">$hitRate%</div><div class="l">Cache hit rate</div></div>
                  <div class="stat"><div class="v">${formatMs(avoidableMs)}</div><div class="l">Avoidable miss duration</div></div>
                </section>
                <main class="grid" id="grid"></main>
                <footer>Durations shown in milliseconds. Charts are interactive (hover for details).</footer>
                <script>
                  const CHARTS = $chartsJson;
                  const palette = ['#6aa6ff','#5ad19a','#f7c948','#ef6f6c','#b48ef0','#4fd1c5','#f6995c','#7e8cff','#e879a6','#9ccc65'];
                  const grid = document.getElementById('grid');
                  CHARTS.forEach(function (c) {
                    const card = document.createElement('div'); card.className = 'card';
                    const h = document.createElement('h2'); h.textContent = c.title; card.appendChild(h);
                    const wrap = document.createElement('div'); wrap.className = 'canvas-wrap';
                    const canvas = document.createElement('canvas'); canvas.id = c.id;
                    wrap.appendChild(canvas); card.appendChild(wrap); grid.appendChild(card);
                    const horizontal = c.indexAxis === 'y';
                    new Chart(canvas, {
                      type: c.type,
                      data: {
                        labels: c.labels,
                        datasets: [{
                          label: c.valueLabel,
                          data: c.data,
                          backgroundColor: c.type === 'doughnut'
                            ? c.labels.map(function (_, i) { return palette[i % palette.length]; })
                            : palette[0],
                          borderWidth: c.type === 'doughnut' ? 1 : 0,
                          borderColor: '#1a1d27'
                        }]
                      },
                      options: {
                        indexAxis: horizontal ? 'y' : 'x',
                        responsive: true, maintainAspectRatio: false,
                        plugins: {
                          legend: { display: c.type === 'doughnut', labels: { color: '#9aa3b2' } }
                        },
                        scales: c.type === 'doughnut' ? {} : {
                          x: { ticks: { color: '#9aa3b2' }, grid: { color: '#2a2e3a' } },
                          y: { ticks: { color: '#9aa3b2' }, grid: { color: '#2a2e3a' } }
                        }
                      }
                    });
                  });
                </script>
                </body>
                </html>
                """.trimIndent()
            )
        }
    }

    private fun buildCharts(): List<ChartSpec> {
        val specs = mutableListOf<ChartSpec>()

        fun addSpec(id: String, type: String, indexAxis: String, title: String, labels: List<String>, data: List<Long>, valueLabel: String) {
            if (labels.isNotEmpty()) specs += ChartSpec(id, type, indexAxis, title, labels, data, valueLabel)
        }

        transforms.durationByTransformActionType().take(10).let { data ->
            addSpec(
                "durationByType", "bar", "x", "Duration by transform type",
                data.map { it.first.extractName() }, data.map { it.second.toLong() }, "Duration (ms)"
            )
        }
        transforms.totalByTransformActionType().take(10).let { data ->
            addSpec(
                "countByType", "bar", "x", "Count by transform type",
                data.map { it.first.extractName() }, data.map { it.second.toLong() }, "Count"
            )
        }
        transforms.durationByAvoidanceOutcome().toList().sortedByDescending { it.second }.let { data ->
            addSpec(
                "durationByAvoidance", "doughnut", "x", "Duration by avoidance outcome",
                data.map { it.first.extractName() }, data.map { it.second.toLong() }, "Duration (ms)"
            )
        }
        transforms.cacheEffectivenessByTransformActionType()
            .filter { it.avoidableMissDuration > 0 }.take(10).let { data ->
                addSpec(
                    "avoidableMisses", "bar", "y", "Avoidable cache-miss duration by type",
                    data.map { it.transformActionType.extractName() },
                    data.map { it.avoidableMissDuration.toLong() }, "Avoidable miss (ms)"
                )
            }
        transforms.durationByAttributeTransition().take(10).let { data ->
            addSpec(
                "attrTransitions", "bar", "y", "Duration by changed-attribute transition",
                data.map { it.first }, data.map { it.second.toLong() }, "Duration (ms)"
            )
        }
        transforms.dependencySortedByDuration().take(10).let { data ->
            addSpec(
                "byDependency", "bar", "y", "Duration by dependency",
                data.map { it.first }, data.map { it.second.toLong() }, "Duration (ms)"
            )
        }
        transforms.sortedByDurationDescending().take(10).let { data ->
            addSpec(
                "slowest", "bar", "y", "Slowest transforms",
                data.map { "${it.transformActionType.extractName()} ${it.artifactTransformExecutionName.substringBefore(" [")}" },
                data.map { it.duration.toIntOrNull()?.toLong() ?: 0L }, "Duration (ms)"
            )
        }
        transforms.durationByBuildScan().take(10).let { data ->
            if (data.size > 1) {
                addSpec(
                    "byBuildScan", "bar", "x", "Duration by build scan",
                    data.map { it.first }, data.map { it.second.toLong() }, "Duration (ms)"
                )
            }
        }
        return specs
    }

    private fun formatMs(ms: Long): String = when {
        ms >= 3_600_000 -> "${(ms / 3_600_000.0).roundTo(1)}h"
        ms >= 60_000 -> "${(ms / 60_000.0).roundTo(1)}m"
        ms >= 1_000 -> "${(ms / 1_000.0).roundTo(1)}s"
        else -> "${ms}ms"
    }

    private fun Double.roundTo(decimals: Int): Double {
        var factor = 1.0
        repeat(decimals) { factor *= 10 }
        return Math.round(this * factor) / factor
    }
}
